### ISSUE TITLE
bold and italic text introduce repetition.

### ISSUE THREAD

**Issue by henkmet** [pfgithub/threadclient#6]
When a text contains italic or bold tags, some words around those tags are repeated. I attach a ss of a comment showing this effect using pfg and the rendering on reddit as reference.
![2022-09-12_094502_506778156](https://user-images.githubusercontent.com/3350726/189560172-0f809fe8-db5b-419b-b588-ce29e1506b7e.png)
![2022-09-12_094455_795711846](https://user-images.githubusercontent.com/3350726/189560179-f4c19a8f-b626-4bef-a14b-aef79f2f7367.png)

**Comment by pfgithub** [comment]
Fixed in a683f837e58cd3d5b412363f9d0dc8b58af39edb / https://github.com/pfgithub/threadclient/commit/bca80b7ba18c74d40c46b96d93d4585788eff845 and released

You can get the update by loading threadclient, waiting a few seconds, and clicking the "Update (refresh)" button in the notification.

![image](https://user-images.githubusercontent.com/6010774/181387400-dccbb711-a5c7-4ebf-801d-d215bee682df.png)
